jacobwilliams/json-fortran

README.md
Do you have any interest in adding some badges (releases/versions, issues, and CI status) to the home page?
Also, waffle.io is a pretty neat and configurable tool to help automate the issue tracking and collaborative work on the issue backlog. It’s pretty easy to learn and straightforwards too.
=> badges and waffle.io

CMakeLists.txt, README.md
Parallel builds were trying to write to the same version of `json_module.mod` at the same time as the static and shared libraries were built, causing the build to fail. By simply telling the compiler to dump the module file in a different location (it’s the same module file after all…) one asynchronous compilation won’t overwrite the other’s work and corrupt the `.mod` file.
=> Fixes CMake parallel build: issue-8

CMakeLists.txt, build.sh
This fixes #53. An extra space was in the Intel flags which was breaking the Intel build in a mysterious way when built with build.sh
=> Broken intel build.sh issue 53

.travis.yml, CMakeLists.txt
This PR makes it so that our travis-ci setup will now test all three build techniques, towards a good CI (#42) setup :
1. build.sh script which uses FoBiS.py
1. CMake build with some unit tests
1. scons build
@jacobwilliams, should you choose to accept this PR, you should adjust your [travis-ci project settings](https://travis-ci.org/jacobwilliams/json-fortran/settings) to allow for at least 3 concurrent jobs, at the bottom of general settings:
This will let the three build systems be tested in parallel.
Right now, just build.sh builds the documentation, so as to not waste time duplicating work and installing ROBODoc in the other builds.
The logic in .travis.yml may not be as readable as it could be. If you think this is the case, I can see if the YAML will be OK with shell if-else-fi …
=> Travis build matrix

.travis.yml, README.md, build.sh, deploy.sh
This adds some functionality discussed in #42.
Before you, @jacobwilliams, can use this, you need to add a secure environment variable to your travis-ci settings for json-fortran that contains a GitHub token with push access to json-fortran. The environment variable containing the token must be called `GH_TOKEN`. 
1. To make a new token, on GitHub.com click the settings icon in the upper right corner —> Applications —> Generate New Token. (It only needs the public_repo access enabled.) Generate the new token then copy the token to your clipboard so you can paste it into travis-ci settings.
1. On travis-ci.org click on the upper right hand Settings button for the repository: Settings —> Settings —> Environment Variables —> Add New Variable and call it `GH_TOKEN`, paste in the token value …
=> Auto deploy script

deploy.sh
This fixes an issue raised in the discussion of PR #59 whereby submitting PRs by @jacobwilliams against the master branch are causing the documentation to be deployed as the master documentation. (This shouldn’t happen until the PR is actually merged!)
I haven’t tested this, but it’s a very simple fix, so it *should* :pray: work
=> Stops PRs by @jacobwilliams from deploying master docs

CMakeLists.txt, README.md, build.sh, cmake/jsonfortran-config.cmake.in
- PR #64 removed json_example, but some references to it still exist in a few places
- Small CMake bug fixed for compiling other projects against the uninstalled
json-fortran build tree.
- Updated info about running the unit tests with SCons (thanks to @bruceravel)
- Minor format updates to README.md
The wiki may still contain references that need to be fixed
=> Clean references to `json_example`

.travis.yml, README.md, src/json_module.f90
- Fixes #67 compile and test example code from README.md
- Small bug fix to dynamically computing the number of digits for real format edit descriptors
- ceiling( log10( ... --> floor( 1 + log10( ...
- consider the case when the number in question is a power of 10 e.g. 100 has 3 digits
=> Test stand alone programs in the README.md

.travis.yml, README.md, build.sh, cmake/pickFortranCompilerFlags.cmake
- Fixes #63 : coverage info
- skips coverage info about the tests, since the tests exist only to test json_module
- currently only one build, the build.sh script will produce the coverage info and
will update coveralls since doing it from multiple builds is redundant.
@jacobwilliams you will need to make a coveralls account and enable json-fortran repo.
=> Added coveralls support for json_module.f90

CMakeLists.txt
This should fix the issue with the new unit test… see my comment on you PR, however, regarding a smart way to go about unit test input/output files in the future.
=> Fixes CMake for jf_test_9.f90

src/json_module.f90
Tested with NAG Fortran Version 6.0.
cmake ../ -DSKIP_DOC_GEN=TRUE -DCMAKE_Fortran_COMPILER=nagfor
Linux Mint 17 64-bit.
=> NAG Fortran Errors on 'module procedure ::' change to 'module procedure' with no double colon

build.sh
Here is the update to build.sh @jacobwilliams asked for….
Also, the css for index.html seems to be broken, and I can’t find where the robodoc output for build.sh is… maybe it doesn’t get generated at the moment?
FYI, you can run `./build.sh --help` to get usage info.
=> Small update

CMakeLists.txt, SConstruct, build.sh, cmake/pickFortranCompilerFlags.cmake
* Silence mysterious intel warning: 5142 "invalid use of $ character"
* Typo in CMakeLists.txt fixed so that build defaults to non-unicode, like build.sh
Fixes #96
=> Small fixes

.travis.yml
Fixes the mysterious travis-ci build error
=> Fix #99 broken travis build

CMakeLists.txt, README.md
Add a CMake option to install to more “normal” GNU type install directory
Add an option to install the ROBODoc generated documentation
This will enable a home-brew install, #98, should home-brew accept my PR for a json-fortran formula (like this one: https://gist.github.com/zbeekman/b45e2a2f914f2820e72e )
=> Gnu install structure

.travis.yml, CMakeLists.txt, CONTRIBUTING.md, README.md
Fixes #103 
- Add `check` target via CMake, so that `make check` after running CMake will build *AND* run the tests. (by default CMake/CTest’s `make test` command does not create a dependency on building the executables needed to do the testing.)
- Remove all test executables from the default `all` target which is run whenever `make` or `make all` is run
- `make test` will still work, but only after all the tests have been build, and these must be built individually, or by running `make check`
The consequences of this are that:
1. If you just want to build (or build and install) the library, you don’t have to wait until all the tests build
2. If you want to build everything and run all the tests you can just type `make check`
=> Make check issue 103

README.md
- Don't forget to update the homebrew forumula via PR when a new
version is tagged.
- Currently the --HEAD option will fail when installing with homebrew
due to the recent resolution of #103. Line # 30 of json-fortran.rb
needs to be replaced with `system "make", "check" if build.with?
"test"` as the `all` target no longer will build the test executables
as per #103
=> update README.md with homebrew info

.travis.yml, build.sh
Inaccurate coverage statistics are reported when optimization is used. Even with the `-coverage` flag to FoBiS.py, an optimization level of `-O2` has been used which causes inlining which in turn decreases the reported coverage. See https://github.com/szaghi/FoBiS/issues/60
Additionally the codecov.io bash script now recursively searches for `.gcno` files and runs gcov on each one it finds. This may cause the unit tests’ coverage to get added to the grand total. To fix this go to the projects codecov.io page and on the right hand side go to ‘Features’ ==> ‘Ignore Files’ and enter something like `src/tests` and hit submit. Now this should display the correct coverage for ONLY `src/json_module.F90`.
A happy side effect of this is that, using the codecov.io browser plugins coverage …
=> Small FoBiS coverage fix

.travis.yml, CMakeLists.txt, cmake/pickFortranCompilerFlags.cmake, src/json_module.F90, src/tests/jf_test_7.f90
I’ve also added a little bit of code to jf_test_7 to verify that you can write json to stderr and to exercise some of the escape_string code.
Btw you may want to turn on and adjust these values too:
https://codecov.io/github/jacobwilliams/json-fortran/features/status
=> fixes 85 allow output to 0 (stderr)

.travis.yml, CHANGELOG.md
- generated with github_changelog_generator then manually edited
This was kind of a pain to do… keeping good issue and PR tagging practices will help in the future.
When changes are made locally don’t forget to update the CHANGELOG, then when the next tag is released the `Unreleased` header can just be changed to the tag name and the link updated and date added. Fixes #120
=> Add a CHANGELOG, Fixes #120

.travis.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, json-fortran.md, src/json_module.F90
CHANGELOG related enhancements including:
- ToC
- Entries in Unreleased that should have been entered in previous commits
- Links to github release under each release
Fortran capitalization updates that escaped my previous PR due to PR refactoring.
Make .travis.yml more legible by breaking shell `if` and `do` statements and long lines, achieved with tricky YAML
=> Changelog and other small fixes

src/json_module.F90, src/tests/jf_test_14.f90
=> New routine to traverse all nodes of a JSON structure.

json-fortran.md
- Fix a broken link on the main page of documentation that should point to the latest release, but was causing a 404
- Relative links to FORD “pages” pages were broken when build tag documentation on travis, since, for tags, we skip actually building the “pages” pages. Now all URLs pointing to “pages” pages in json-module.md use a full URL to the “pages” published with the latest master branch. URLs in the source code should follow this convention too, if they point to FORD “pages” pages.
- Actually process and build test documentation with FORD
- Add a more prominent link to the `json_module` module documentation on the main page.
- Some other smallish cleanups.
Let me know if you think it’s worth while releasing a minor patch release for these changes as well as your changes since the …
=> Tag documentation fix

json-fortran.md
Put meta data in a table, rather than a jumbled paragraph when viewing on Github.com
=> Make FORD project file legible on github

README.md
braumeister added a new API, and shields.io added a new badge to track available versions on homebrew.
=> Add homebrew version badge

src/json_string_utilities.F90
Note that I added a compiler directive so that the workaround is only used when compiling with Gfortran (any version).
=> Added a workaround for a Gfortran 6.1 bug. Fixes #186.

CMakeLists.txt, build.sh, deploy.sh, json-fortran.md, preprocessor-def.md
FORD has introduced some sort of regression that causes it to fail when processing the unicode enabled JSON-Fortran... and maybe the normal JSON-Fortran...
There's no downside of always passing `--debug` to FORD, AFAICT, so I've added it to the CMake and build.sh scripts...
We should probably wait until FORD gets fixed to merge this... and also make sure that we re-trigger the CI builds after FORD is fixed, otherwise the documentation may be incorrect...
See https://github.com/cmacmackin/ford/issues/139#issuecomment-223824644 for more info....
=> De-lint shell scripts with spellcheck and debug FORD upgrade

src/json_file_module.F90, src/json_value_module.F90, src/tests/jf_test_14.f90, src/tests/jf_test_3.f90
* Added `traverse` method to `json_file`.
* Added new methods to get and set the `json_core` in a `json_file`.
Fixes #204
=> JSON file traverse

src/json_value_module.F90, src/tests/jf_test_1.f90
=> compact_reals and real_format='*' can now be used at the same time.

src/json_file_module.F90, src/json_initialize_arguments.inc, src/json_value_module.F90, src/tests/jf_test_23.f90
=> added path_mode integer input

src/json_initialize_arguments.inc, src/json_value_module.F90
=> Disable comments using blank comment_char

src/json_file_module.F90, src/json_value_module.F90, src/tests/jf_test_26.f90
Added methods to add variables by specifying their paths. Fixes #268.
Changed argument to `update` methods from “name” to “path” to match the recent change in `json_value_module`.
Some minor formatting and commenting updates.
=> json_file updates

CMakeLists.txt
CMAKE_INSTALL_LIBDIR is empty unless USE_GNU_INSTALL_CONVENTION is true, and in both cases INSTALL_LIB_DIRS is set.
=> Replace CMAKE_INSTALL_LIBDIR with INSTALL_LIB_DIR

CMakeLists.txt, cmake/pickFortranCompilerFlags.cmake, files/expected-outputs/hello-world-ascii.json, files/expected-outputs/hello-world-ucs4.json, files/expected-outputs/test2.json
Hi @jacobwilliams, we're using json-fortran for a contract I'm currently working on. As a requirement we have to build software on windows, and with MSVS. There were a few places where the CMake build was having trouble generating & running MSVS solutions on Windows with the latest Intel 18 compilers. I have fixed these issues on our fork, and wanted to contribute this back upstream.
Thanks,
Zaak
=> CMake on windows (MSVS solutions)

CMakeLists.txt
- MSVS will install, e.g., `$<prefix>/include/Debug/json_file_module.mod`
- We should strip the build config directory that IDEs like MSVS add when doing an installation
=> Only install module files, not config dir with IDE

src/json_file_module.F90, src/tests/jf_test_41.F90
=> Added a character=json_file assignment operator.

.travis.yml
Fixes #180 
Now testing gfortran 6-9.
=> Expanded compiler tests on travis

CMakeLists.txt, cmake/jsonfortran-config.cmake.in, cmake/pkg/jsonfortran-config.cmake.in, cmake/uninstall.cmake.in
Replace references to variables `CMAKE_{NAME,SOURCE_DIR,BINARY_DIR}`
with `PROJECT_{NAME,SOURCE_DIR,BINARY_DIR}`.  The latter are set
by our `project(jsonfortran)` call and work even when jsonfortran
is configured under an `add_subdirectory` call of another project.
=> cmake: Enable building jsonfortran as a subdirectory of another project.

src/json_value_module.F90, src/tests/jf_test_44.F90, visual_studio/jsonfortrantest/jsonfortrantest.f90, visual_studio/jsonfortrantest/jsonfortrantest.vfproj
=> made json_get_array recursive

src/json_parameters.F90, src/json_value_module.F90, src/tests/jf_test_44.F90, src/tests/jf_test_45.F90
=> Fixed json_get_path output for arrays of arrays

src/json_initialize_arguments.inc, src/json_value_module.F90
By default, it will now use '/!#'. Fixes #456
=> added support for multiple comment characters

src/json_file_module.F90, src/json_get_scalar_by_path.inc, src/json_get_vec_by_path.inc, src/json_get_vec_by_path_alloc.inc, src/json_value_module.F90, src/tests/jf_test_46.F90, visual_studio/jsonfortrantest/jsonfortrantest.f90, visual_studio/jsonfortrantest/jsonfortrantest.vfproj
Fixes #208. Adds a `default` optional argument to the `json_get_*_by_path` routines. To make it easier to set values that aren't found in file, with only one line of code.
This also consolidates some duplicated code into include files.
=> adding default optional args to get by path routines

src/json_file_module.F90, src/tests/jf_test_46.F90
=> added a string to json_file assignment operator.

src/json_value_module.F90, src/tests/jf_test_27.F90
now, a mixed array of ints and reals will now also be compressed if this option is enabled. Fixes #470
=> update for compress_vectors

README.md
In case this is of interest, *json-fortran* can now be installed via *conda-forge*. I currently build for Linux (x86_64, aarch64, ppc64le) and MacOS (x86_64, arm64), if there is interest I can try to build it with flang on Windows.
=> Add information on conda-forge distribution

CMakeLists.txt, README.md
- add `BUILD_INTERFACE` for finding modules in build directory
- add `INSTALL_INTERFACE` to associate include directory with target
- add namespace to exported target
- `jsonfortran::jsonfortran` target instead of `jsonfortran`
- `jsonfortran::jsonfortran-static` target instead of `jsonfortran-static`
Closes #503
=> Export include directories with target

src/json_parameters.F90
Hello,
When compiling JSON-Fortran with the [nvfortran](https://docs.nvidia.com/hpc-sdk/index.html) compiler, I ran into the following errors:
1.
```
NVFORTRAN-S-0026-Unmatched quote (/home/yu/opt/json-fortran/src/json_parameters.F90: 61)
```
Change: Partly reverted commit 90fee68f02.
2.
```
NVFORTRAN-S-0188-Argument number 2 to add_to_path: type mismatch (/home/yu/opt/json-fortran/src/json_value_module.F90: 7875)
```
Change: Removed an optional argument that is not used anyway.
With these changes, JSON-Fortran compiles with nvfortran 21.5 and 21.7.
Feel free to close if support for nvfortran is not of interest.
Thanks!
=> Minor changes for nvfortran

src/json_module.F90, src/tests/jf_test_01.F90
=> 505 version 2

README.md
This creates a `#json-fortran` target, allowing the "top" links and the ToC link in the readme to work properly.
=> Fix readme heading so "top" links work

CMakeLists.txt, README.md, fpm.toml, json-fortran.fobis, src/json_value_module.F90, src/tests/jf_test_01.F90, src/tests/jf_test_02.F90, src/tests/jf_test_03.F90, src/tests/jf_test_04.F90, src/tests/jf_test_05.F90, src/tests/jf_test_06.F90, src/tests/jf_test_09.F90, src/tests/jf_test_10.F90, src/tests/jf_test_11.F90, src/tests/jf_test_12.F90, src/tests/jf_test_14.F90, src/tests/jf_test_21.F90, src/tests/jf_test_22.F90, src/tests/jf_test_23.F90, src/tests/jf_test_48.F90
Dear @jacobwilliams,
I have added tests to the `fpm.toml` file and updated CMake and FoBiS tests for compatibility.
All tests passed successfully with fpm, CMake, and FoBis on my Linux system.
Best regards,
Ali
=> Add tests to fpm.toml file

src/json_string_utilities.F90
This solves an issue when IEEE floating-point rounding mode is manually set to `IEEE_DOWN`.
The original code in the `string_to_integer` subroutine
```fortran
ndigits_digits = floor(log10(real(ndigits)))+1
```
erroneously returns 1 even when `ndigits` is 10 (while the correct value should be 2).
The following code is the minimum reproducible example of the problem.
The last `deserialize` will result in a crush.
```fortran
program jsontest
use :: ieee_arithmetic
use :: json_module
type(json_file) :: file
call ieee_set_rounding_mode(ieee_down) 
call file%initialize()
call file%deserialize('{"foo" : 100}')
print *, "ok 1"
call file%deserialize('{"foo" : 100, "bar" : 1000}')
print *, "ok 2"
call file%deserialize('{"foo" : 100, "bar" : 1000, "baz" : 10000}')
print *, "ok 3"
call file%destroy() …
```
=> Fixed an issue when IEEE floating-point rounding mode is IEEE_DOWN

.VERSION.in, CMakeLists.txt, packaging/CMakeLists.txt, pages/development-resources/release-checklist.md
this is #533 plus some minor edits
=> Develop cmake updates

CMakeLists.txt
I have found some issues trying to compile with the recent Intel One API + Visual Studio 2022. Basically I got this error.
```
1> [CMake]   failed with:
1> [CMake] 
1> [CMake]    ninja: error: build.ninja:280: multiple rules generate jsonfortran.lib
```
I have implemented some changes in CMakeLists.txt to fix it by considering the case of IntelLLVM which is the compiler Id of the new compiler.
Best regards,
Luis
=> Fixes compilation with Ninja and IntelLLVM when using OneAPI

CMakeLists.txt
The package version was not set correctly, which caused the cmake configuration files to be saved to a folder with blank version name.
=> Fix version variable name.

src/json_file_module.F90
To prevent a memory leak if the type is used later to load another file. Fixes #561
=> destroy pointer in json_file before loading

.github/workflows/CI.yml, fpm.toml, src/json_initialize_arguments.inc, src/json_initialize_dummy_arguments.inc, src/json_value_module.F90, src/tests/jf_test_51.F90, visual_studio/jsonfortrantest/jsonfortrantest.vfproj
can be used to disallow extra trailing commas in arrays and objects (it is true by default and thus allowed) Fixes #569
=> added an optional allow_trailing_comma flag

src/json_file_module.F90
If nullify_pointer is False, the pointer is not nullified 
Fixes #564
=> add a new option to json_file constructor

src/json_file_module.F90
=> added destroy_pointer option to json_file load

src/json_value_module.F90
We have noticed a couple of issues with large temporary strings inside of json-fortran causing stackoverflows on Windows builds with ifort. Basically all places where a string that could be very large (e.g. the entire JSON representation as one string) ends up in a temporary could overflow the stack.
I have workarounds in two places in this pull request. For our usage, that resolved the issues on Windows builds with iforts. I did not go through the rest of the codebase to scan for similar places that might be prone to overflowing.
=> Workarounds for stack overflows on Windows when using ifort

src/json_value_module.F90
=> added some iostat checks to write statements to avoid potential crashes

.github/workflows/CI.yml
see if this clears the commit history. Fixes #583
=> set single-commit=true for doc branch

src/json_value_module.F90
=> fixed error when using non-default ints
