jacobwilliams/json-fortran

src/json_module.f90

Updates to new real number formatting feature

---

build.sh
robodoc.rc
src/json_module.f90
src/tests/jf_test_9.f90

- Silenced ifort long line error
- line ending cleanup
- add FoBiS.py flags to trigger recompilation when flags/compiler changes
see also https://github.com/szaghi/FoBiS/issues/45 and https://github.com/szaghi/FoBiS/issues/46
- told ROBODoc to ignore Emacs file backups

Small changes and fixes:

---

build.sh

- Allows easier control of build options
- prepares for unicode support
note: in a sense this breaks backwards compatibility because now instead of `./build.sh -ifort` one must do something like `./build.sh --compiler ifort` (Intel or intel work too)

Command line parsing for build.sh

---

src/json_module.F90
src/tests/jf_test_11.F90
src/tests/jf_test_9.f90

Some refactoring for increased runtime speed.
This includes reducing the number of string reallocations, and also a new STREAM read mode for non-unicode files.  More changes to come...

Unicode speed

---

README.md

- Added table of contents to README.md… I can remove or change if you like
- Added note about NAG
- Updated CMake example to work with alternate install structure

Readme toc

---

CONTRIBUTING.md
README.md
src/json_module.F90
src/tests/jf_test_7.f90

- Fixed some documentation errors, and improved documentation
- Removed dead code `add_character_to_string`
- Hacked on jf_test_7.f90 to increase coverage

Documentation fixes & coverage improvements

---

LICENSE
src/json_module.F90
src/tests/jf_test_1.f90
src/tests/jf_test_10.f90
src/tests/jf_test_11.F90
src/tests/jf_test_2.f90
src/tests/jf_test_3.f90
src/tests/jf_test_4.f90
src/tests/jf_test_5.f90
src/tests/jf_test_6.f90
src/tests/jf_test_7.f90
src/tests/jf_test_8.f90
src/tests/jf_test_9.f90

- Fixes #118
Will need to be careful when updating and merging FORD branches

Correct Spelling of Fortran

---

.travis.yml

Fix #127 broken travis build

---

CHANGELOG.md
build.sh
json-fortran.md
pages/development-resources/release-checklist.md
pages/index.md
pages/releases/index.md

misc fixes/improvements to FORD documentation
small build.sh bug fix

Documentation fixes

---

src/json_module.F90
src/tests/jf_test_13.f90

Fixes #157.
Added an option to output real numbers with fmt=* formatting.

Fixed a bug where some real numbers weren't being read in properly.

---

src/json_module.F90

String parse

---

src/json_file_module.F90
src/json_value_module.F90

json_core updates

---

src/json_value_module.F90
src/tests/jf_test_16.f90

Added swap routine. Fixes #177
Other related changes.

Swap routine

---

src/json_string_utilities.F90
src/json_value_module.F90

Gfortran bugs

---

src/json_file_module.F90
src/json_parameters.F90
src/json_string_utilities.F90
src/json_value_module.F90
src/tests/jf_test_16.f90
src/tests/jf_test_17.f90
src/tests/jf_test_18.f90

Name searching options

---

.travis.yml
build.sh
codecov.yml
pages/development-resources/json_module.F90.gcov.md

See issue #174 
See issue #188

Getting codecov working again

---

src/json_string_utilities.F90

This is really just to test the coverage.

minor commenting changes.

---

files/inputs/test2.json
src/json_value_module.F90
src/tests/jf_test_2.f90

API for adding a null variable

---

src/json_file_module.F90
src/json_value_module.F90
src/tests/jf_test_1.f90

Added new option to print JSON without extra whitespace

---

src/json_module.F90
src/json_parameters.F90
src/json_value_module.F90

Moved some parameters into the json_parameters module

---

src/json_value_module.F90
src/tests/jf_test_20.f90

Insert routine

---

src/json_parameters.F90
src/tests/jf_test_21.f90

Real format fix

---

build.sh
src/json_kinds.F90

added support in the code for specifying the real and integer kinds

---

CMakeLists.txt
json-fortran.pc.cmake.in

Adds a [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/)  file for the library. Helpful for those use Makefiles and link with json-fortran.

Add pkg-config file

---

src/json_file_module.F90
src/json_initialize_arguments.inc
src/json_parameters.F90
src/json_value_module.F90
src/tests/jf_test_1.f90

Added option to change default path sep character.

---

src/json_value_module.F90

Fixed an issue with indenting of arrays within arrays.

---

src/json_file_module.F90
src/json_initialize_arguments.inc
src/json_value_module.F90
src/tests/jf_test_27.f90

Added support for printing vectors on one line.
Fixes #228

Compress vectors

---

src/json_value_module.F90

Fixed an issue where the char_count wasn’t always correct

---

src/json_value_module.F90
src/tests/jf_test_1.f90

Zero-length arrays

---

src/json_value_module.F90
src/tests/jf_test_28.f90

added routine to reverse vector or object.

---

src/json_file_module.F90
src/json_string_utilities.F90
src/json_value_module.F90
src/tests/jf_test_2.f90
src/tests/jf_test_23.f90

Escape fix

---

src/json_file_module.F90
src/json_initialize_arguments.inc
src/json_value_module.F90
src/tests/jf_test_29.f90
src/tests/jf_test_3.f90
src/tests/jf_test_8.f90

Check for duplicate keys.

---

files/inputs/test1.json
src/json_parameters.F90
src/json_value_module.F90
src/tests/jf_test_1.f90
src/tests/jf_test_24.F90

WIP: Bracket Notation

---

README.md
json-fortran.fobis

Added a fobis file.

---

src/json_file_module.F90
src/json_initialize_arguments.inc
src/json_value_module.F90

Fixes #323
Fixes #324 
Fixes #326

various updates

---

src/json_value_module.F90
src/tests/jf_test_33.F90

json_clone fix

---

src/json_value_module.F90
src/tests/jf_test_35.F90

Destroy a malformed JSON structure

---

src/json_parameters.F90
src/json_value_module.F90
visual_studio/jsonfortrantest/jsonfortrantest.f90
visual_studio/jsonfortrantest/jsonfortrantest.vfproj

Dangling pointer issue

---

src/json_parameters.F90
src/json_value_module.F90
src/tests/jf_test_36.F90
visual_studio/jsonfortrantest/jsonfortrantest.f90
visual_studio/jsonfortrantest/jsonfortrantest.vfproj

Print to string speedup

---

CMakeLists.txt
src/json_file_module.F90
src/json_kinds.F90
src/json_module.F90
src/json_parameters.F90
src/json_value_module.F90
src/tests/jf_test_10.F90
src/tests/jf_test_12.F90
src/tests/jf_test_15.F90
src/tests/jf_test_24.F90
src/tests/jf_test_32.F90
src/tests/jf_test_38.F90

WIP: Support for multiple real kinds

---

src/json_value_module.F90

401 get by index

---

.github/CONTRIBUTING.md
README.md
pages/development-resources/release-checklist.md
pages/development-resources/travis.yml.md

Migrate to travis-ci.com

---

src/json_initialize_arguments.inc
src/json_initialize_dummy_arguments.inc
src/json_value_module.F90
src/tests/jf_test_43.F90
visual_studio/jsonfortrantest/jsonfortrantest.f90
visual_studio/jsonfortrantest/jsonfortrantest.vfproj

If the parsing of an integer fails, it can try to parse it as a real. Fixes #444

added a new option for integer parsing.

---

src/json_value_module.F90

Real to int conversion

---

CMakeLists.txt

updated cmake for compatibility with older versions < 3.7

---

src/json_value_module.F90

Fix for a memory leak when parsing an empty array

---

src/json_value_module.F90
src/tests/jf_test_02.F90
src/tests/jf_test_10.F90
src/tests/jf_test_12.F90
src/tests/jf_test_14.F90
src/tests/jf_test_20.F90
src/tests/jf_test_34.F90
src/tests/jf_test_35.F90
src/tests/jf_test_44.F90
src/tests/jf_test_47.F90
visual_studio/jsonfortranlib/jsonfortranlib.vfproj
visual_studio/jsonfortrantest/jsonfortrantest.vfproj

Fixing some memory issues in the unit tests

---

src/json_file_module.F90

a minor change to work around a possible compiler bug in Gfortran
